"""modulo de caixa

Revision ID: 39ab0b1d843c
Revises: 6f8e54f69113
Create Date: 2026-08-07 10:20:45.760503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ab0b1d843c'
down_revision: Union[str, Sequence[str], None] = '6f8e54f69113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caixa_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('renda_bruta_tipica', sa.BigInteger(), nullable=False),
    sa.Column('origem_renda', sa.String(length=30), nullable=False),
    sa.Column('imposto_reservado', sa.BigInteger(), nullable=False),
    sa.Column('renda_liquida', sa.BigInteger(), nullable=False),
    sa.Column('essenciais', sa.BigInteger(), nullable=False),
    sa.Column('nao_essenciais', sa.BigInteger(), nullable=False),
    sa.Column('provisao_mensal', sa.BigInteger(), nullable=False),
    sa.Column('aporte_reserva', sa.BigInteger(), nullable=False),
    sa.Column('aporte_aposentadoria', sa.BigInteger(), nullable=False),
    sa.Column('comprometido_dividas', sa.BigInteger(), nullable=False),
    sa.Column('capacidade_hoje', sa.BigInteger(), nullable=False),
    sa.Column('capacidade_maxima', sa.BigInteger(), nullable=False),
    sa.Column('aporte_maximo', sa.BigInteger(), nullable=False),
    sa.Column('minimo_existencial', sa.BigInteger(), nullable=True),
    sa.Column('nao_fecha', sa.Boolean(), nullable=False),
    sa.Column('calculado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caixa_snapshot_tenant_id'), 'caixa_snapshot', ['tenant_id'], unique=False)
    op.create_table('fonte_renda',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor_tipico_informado', sa.BigInteger(), nullable=True),
    sa.Column('variavel', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fonte_renda_tenant_id'), 'fonte_renda', ['tenant_id'], unique=False)
    op.create_table('gasto',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('essencial', sa.Boolean(), nullable=False),
    sa.Column('fixo', sa.Boolean(), nullable=False),
    sa.Column('valor_mensal', sa.BigInteger(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gasto_tenant_id'), 'gasto', ['tenant_id'], unique=False)
    op.create_table('provisao_anual',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('valor_anual', sa.BigInteger(), nullable=False),
    sa.Column('mes_vencimento', sa.Integer(), nullable=False),
    sa.Column('saldo_acumulado', sa.BigInteger(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provisao_anual_tenant_id'), 'provisao_anual', ['tenant_id'], unique=False)
    op.create_table('recebimento',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('fonte_id', sa.String(length=36), nullable=False),
    sa.Column('mes', sa.String(length=7), nullable=False),
    sa.Column('valor', sa.BigInteger(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recebimento_fonte_id'), 'recebimento', ['fonte_id'], unique=False)
    op.create_index(op.f('ix_recebimento_tenant_id'), 'recebimento', ['tenant_id'], unique=False)
    op.add_column('perfil', sa.Column('imposto_bps', sa.Integer(), nullable=True))
    op.add_column('perfil', sa.Column('reserva_meta_meses', sa.Integer(), nullable=True))
    op.add_column('perfil', sa.Column('reserva_saldo', sa.BigInteger(), nullable=True))
    op.add_column('perfil', sa.Column('reserva_aporte', sa.BigInteger(), nullable=True))
    op.add_column('perfil', sa.Column('aposentadoria_aporte', sa.BigInteger(), nullable=True))
    op.add_column('perfil', sa.Column('rendimento_esperado_bps', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # MIGRAÇÃO DE DADO, escrita à mão: a renda que já estava no perfil vira uma
    # fonte de renda. Sem isto, quem já informou a renda abre o módulo de caixa
    # e vê zero — e um zero onde havia número é indistinguível de um bug.
    #
    # `renda_mensal` NÃO é removida da tabela: ela continua sendo lida por
    # `GET /v1/perfil`, agora derivada da soma das fontes ativas. Apagá-la aqui
    # quebraria o app instalado no aparelho de quem não atualizou.
    op.execute(
        """
        INSERT INTO fonte_renda (
            id, tenant_id, nome, tipo, valor_tipico_informado, variavel, ativo
        )
        SELECT
            CAST(gen_random_uuid() AS VARCHAR(36)),
            tenant_id,
            'Renda informada',
            'outro',
            renda_mensal,
            FALSE,
            TRUE
        FROM perfil
        WHERE renda_mensal IS NOT NULL AND renda_mensal > 0
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfil', 'rendimento_esperado_bps')
    op.drop_column('perfil', 'aposentadoria_aporte')
    op.drop_column('perfil', 'reserva_aporte')
    op.drop_column('perfil', 'reserva_saldo')
    op.drop_column('perfil', 'reserva_meta_meses')
    op.drop_column('perfil', 'imposto_bps')
    op.drop_index(op.f('ix_recebimento_tenant_id'), table_name='recebimento')
    op.drop_index(op.f('ix_recebimento_fonte_id'), table_name='recebimento')
    op.drop_table('recebimento')
    op.drop_index(op.f('ix_provisao_anual_tenant_id'), table_name='provisao_anual')
    op.drop_table('provisao_anual')
    op.drop_index(op.f('ix_gasto_tenant_id'), table_name='gasto')
    op.drop_table('gasto')
    op.drop_index(op.f('ix_fonte_renda_tenant_id'), table_name='fonte_renda')
    op.drop_table('fonte_renda')
    op.drop_index(op.f('ix_caixa_snapshot_tenant_id'), table_name='caixa_snapshot')
    op.drop_table('caixa_snapshot')
    # ### end Alembic commands ###
