"""parcelas, renegociacao e preferencias de lembrete

Revision ID: 6fda82cf2b09
Revises: 8864a227fc79
Create Date: 2026-08-06 11:40:22.005018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fda82cf2b09'
down_revision: Union[str, Sequence[str], None] = '8864a227fc79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcela',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('divida_id', sa.String(length=36), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('valor', sa.BigInteger(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('paga_em', sa.Date(), nullable=True),
    sa.Column('valor_pago', sa.BigInteger(), nullable=True),
    sa.Column('cancelada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcela_divida_id'), 'parcela', ['divida_id'], unique=False)
    op.create_index(op.f('ix_parcela_tenant_id'), 'parcela', ['tenant_id'], unique=False)
    op.create_table('renegociacao',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('divida_id', sa.String(length=36), nullable=False),
    sa.Column('valor_anterior', sa.BigInteger(), nullable=False),
    sa.Column('novo_valor', sa.BigInteger(), nullable=False),
    sa.Column('novo_total_parcelas', sa.Integer(), nullable=False),
    sa.Column('nova_taxa_juros_mensal', sa.Integer(), nullable=True),
    sa.Column('primeiro_vencimento', sa.Date(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renegociacao_divida_id'), 'renegociacao', ['divida_id'], unique=False)
    op.create_index(op.f('ix_renegociacao_tenant_id'), 'renegociacao', ['tenant_id'], unique=False)
    op.add_column('perfil', sa.Column('hora_lembrete', sa.String(length=5), server_default='09:00', nullable=False))
    op.add_column('perfil', sa.Column('dias_antecedencia_lembrete', sa.Integer(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfil', 'dias_antecedencia_lembrete')
    op.drop_column('perfil', 'hora_lembrete')
    op.drop_index(op.f('ix_renegociacao_tenant_id'), table_name='renegociacao')
    op.drop_index(op.f('ix_renegociacao_divida_id'), table_name='renegociacao')
    op.drop_table('renegociacao')
    op.drop_index(op.f('ix_parcela_tenant_id'), table_name='parcela')
    op.drop_index(op.f('ix_parcela_divida_id'), table_name='parcela')
    op.drop_table('parcela')
    # ### end Alembic commands ###
