"""inicial

Revision ID: 8864a227fc79
Revises: 
Create Date: 2026-08-06 11:14:35.566435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8864a227fc79'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divida',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('credor', sa.String(length=200), nullable=False),
    sa.Column('valor_cobrado', sa.BigInteger(), nullable=False),
    sa.Column('data_origem', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('taxa_juros_mensal', sa.Integer(), nullable=True),
    sa.Column('total_parcelas', sa.Integer(), nullable=True),
    sa.Column('parcelas_pagas', sa.Integer(), nullable=True),
    sa.Column('proximo_vencimento', sa.Date(), nullable=True),
    sa.Column('situacao', sa.String(length=20), nullable=False),
    sa.Column('valor_pago', sa.BigInteger(), nullable=True),
    sa.Column('data_quitacao', sa.Date(), nullable=True),
    sa.Column('extracao_id', sa.String(length=36), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('excluido_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divida_tenant_id'), 'divida', ['tenant_id'], unique=False)
    op.create_table('extracao',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('campos_json', sa.Text(), nullable=True),
    sa.Column('alertas_json', sa.Text(), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=300), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('arquivo_descartado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracao_tenant_id'), 'extracao', ['tenant_id'], unique=False)
    op.create_table('perfil',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('renda_mensal', sa.BigInteger(), nullable=True),
    sa.Column('dependentes', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('saldo_snapshot',
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('mes', sa.String(length=7), nullable=False),
    sa.Column('saldo', sa.BigInteger(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id', 'mes')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saldo_snapshot')
    op.drop_table('perfil')
    op.drop_index(op.f('ix_extracao_tenant_id'), table_name='extracao')
    op.drop_table('extracao')
    op.drop_index(op.f('ix_divida_tenant_id'), table_name='divida')
    op.drop_table('divida')
    # ### end Alembic commands ###
